# %%
import itertools

import numpy as np
import pandas as pd
import xarray as xr

FAO2EUMOFA = {
    # Dictionary mapping species from FAO to EUMOFA/export data
    # key : value
    # -----------
    # Exports : FAO
    "Abalone": ["Tuberculate abalone", "Abalones nei"],
    "Alaska pollock": ["Alaska pollock(=Walleye poll.)"],
    "Anchovy": ["European anchovy"],
    "Blue whiting": ["Blue whiting(=Poutassou)"],
    "Carp": [
        "Common carp",
        "Crucian carp",
        "Carpet shells nei",
        "Grooved carpet shell",
        "Japanese carpet shell",
        "Banded carpet shell",
        "Grass carp(=White amur)",
        "Silver carp",
        "Bighead carp",
        "Golden carpet shell",
    ],
    "Caviar, livers and roes": [],
    "Clam": [
        "Arched razor shell",
        "Banded carpet shell",
        "Clams, etc. nei",
        "Carpet shells nei",
        "Common edible cockle",
        "Cockles nei",
        "Donax clams",
        "European razor clam",
        "Golden carpet shell",
        "Granular top-shell",
        "Grooved carpet shell",
        "Hungarian cap-shell",
        "Japanese carpet shell",
        "Mactra surf clams nei",
        "Manila clam",
        "Marine shells nei",
        "Northern quahog(=Hard clam)",
        "Olive green cockle",
        "Pod razor shell",
        "Razor clams, knife clams nei",
        "Sand cockle",
        "Solen razor clams nei",
        "Surf clams nei",
        "Solid surf clam",
        "Stimpson's surf clam",
        "Sword razor shell",
        "Subtruncate surf clam",
        "Truncate donax",
        "Tuberculate cockle",
        "Venus clams nei",
    ],
    "Cobia": ["Cobia"],
    "Cod": [
        "Atlantic cod",
        "Poor cod",
        "Tadpole codling",
        "Greenland cod",
        "Marbled rockcod",
        "Humped rockcod",
        "Striped-eyed rockcod",
        "Crocodile icefishes nei",
        "Pacific cod",
        "Polar cod",
        "Antarctic rockcods, noties nei",
        "Yellowbelly rockcod",
        "Black rockcod",
        "Moray cods nei",
        "Brazilian codling",
        "Crocodile shark",
        "Smalleye moray cod",
        "North Atlantic codling",
        "Patagonian rockcod",
        "Longtail Southern cod",
        "Red codling",
        "Striped rockcod",
    ],
    "Crab": [
        "Edible crab",
        "Spinous spider crab",
        "Marine crabs nei",
        "Stone king crab",
        "Portunus swimcrabs nei",
        "Green crab",
        "Mediterranean shore crab",
        "Velvet swimcrab",
        "Right-handed hermit crabs nei",
        "Deep-sea red crab",
        "Swimming crabs, etc. nei",
        "Tanner crabs nei",
        "King crabs, stone crabs nei",
        "Chinese mitten crab",
        "Queen crab",
        "Red king crab",
        "Henslow’s swimming crab",
        "Shamefaced crab",
        "West african fiddler crab",
        "Atlantic rock crab",
        "Knobby swimcrab",
        "Blue crab",
        "Blue-leg swimcrab",
        "Maja spider crabs nei",
        "Common spider crab",
        "King crabs nei",
        "King crab",
        "Antarctic stone crab",
        "Red crab",
        "Southwest Atlantic red crab",
        "King crabs",
        "Red stone crab",
        "Globose king crab",
    ],
    "Cusk-eel": [
        "Pink cusk-eel",
        "Cusk-eels nei",
        "Pudgy cuskeel",
    ],
    "Cuttlefish": [
        "Common cuttlefish",
        "Cuttlefish, bobtail squids nei",
        "Elegant cuttlefish",
        "Pink cuttlefish",
        "Cuttlefishes nei",
        "African cuttlefish",
    ],
    "Dogfish": [
        "Dogfishes and hounds nei",
        "Picked dogfish",
        "Dogfish sharks nei",
        "Birdbeak dogfish",
        "Arrowhead dogfish",
        "Portuguese dogfish",
        "Longnose velvet dogfish",
        "Knifetooth dogfish",
        "Black dogfish",
        "Dogfishes nei",
        "Dogfish sharks, etc. nei",
        "Rough longnose dogfish",
    ],
    "Eel": [
        "European eel",
        "Eelpout",
        "Sandeels(=Sandlances) nei",
        "Eelpouts",
        "Conger eels nei",
        "Conger eels, etc. nei",
        "Painted eel",
        "Small sandeel",
        "Mediterranean sand eel",
        "Smooth sandeel",
        "Muddy arrowtooth eel",
        "Kaup's arrowtooth eel",
    ],
    "Fish oil": [],
    "Fishmeal": [],
    "Flounder, European": ["European flounder"],
    "Flounder, other": [
        "Witch flounder",
        "Lefteye flounders nei",
        "Righteye flounders nei",
        "Winter flounder",
        "Spotted flounder",
        "Yellowtail flounder",
        "Summer flounder",
        "Wide-eyed flounder",
        "Antarctic armless flounder",
    ],
    "Freshwater catfish": [
        "Wels(=Som) catfish",
    ],
    "Freshwater crayfish": [
        "Signal crayfish",
        "Euro-American crayfishes nei",
        "White-clawed crayfish",
        "Noble crayfish",
    ],
    "Grenadier": [
        "Roundnose grenadier",
        "Patagonian grenadier",
        "Grenadiers nei",
        "Roughhead grenadier",
        "Common Atlantic grenadier",
        "Blue grenadier",
        "Bigeye grenadier",
        "Roughsnout grenadier",
        "Softhead grenadier",
        "Western softhead grenadier",
        "Whitson's grenadier",
    ],
    "Haddock": ["Haddock"],
    "Hake": [
        "European hake",
        "White hake",
        "Hakes nei",
        "Cape hakes",
        "Argentine hake",
        "Red hake",
        "Senegalese hake",
        "Silver hake",
        "South Pacific hake",
        "North Pacific hake",
        "Southern hake",
        "Longfin hake",
        "Merluccid hakes nei",
        "Benguela hake",
        "Deep-water Cape hake",
        "Shallow-water Cape hake",
    ],
    "Halibut, Atlantic": ["Atlantic halibut"],
    "Halibut, Greenland": ["Greenland halibut"],
    "Halibut, other": [],
    "Herring": ["Atlantic herring", "Pacific herring", "Whitehead's round herring"],
    "Horse mackerel, Atlantic": ["Atlantic horse mackerel"],
    "Horse mackerel, other": [
        "Jack and horse mackerels nei",
        "Mediterranean horse mackerel",
        "Cape horse mackerel",
        "Cunene horse mackerel",
    ],
    "Jellyfish": ["Common jellyfish", "Jellyfishes nei"],
    "Ling": [
        "Grayling",
        "Ling",
        "Blue ling",
        "Tadpole codling",
        "Spanish ling",
        "Rocklings nei",
        "Lings nei",
        "Brazilian codling",
        "North Atlantic codling",
        "Threadfin rockling",
        "Mediterranean bigeye rockling",
        "Bigeye rockling",
        "Shore rockling",
        "Three-bearded rockling",
        "Fivebeard rockling",
        "Red codling",
    ],
    "Lobster Homarus spp": ["Homarus lobsters nei"],
    "Lobster, Norway": ["Norway lobster"],
    "Mackerel": [
        "Atlantic mackerel",
        "Atlantic chub mackerel",
        "Mackerel icefish",
        "Narrow-barred Spanish mackerel",
        "West African Spanish mackerel",
        "Mackerels nei",
        "Pacific chub mackerel",
        "Atka mackerel",
        "Snake mackerels, escolars nei",
        "Chilean jack mackerel",
        "Pacific jack mackerel",
        "Scomber mackerels nei",
        "Blue jack mackerel",
        "Mackerel sharks,porbeagles nei",
    ],
    "Megrim": ["Megrim", "Megrims nei", "Four-spot megrim"],
    "Miscellaneous small pelagics": [],  # we can safely assume 100 % marine
    "Molluscs and aquatic invertebrates, other": [
        "Marine molluscs nei",
        "Freshwater molluscs nei",
    ],
    "Monk": ["Monkfishes nei", "Angler(=Monk)"],
    "Mussel Mytilus spp": [
        "Sea mussels nei",
        "Mediterranean mussel",
        "Blue mussel",
        "Mytilus mussels nei",
    ],
    "Mussel, other": [
        "Horse mussels nei",
        "European date mussel",
    ],
    "Nile perch": [],
    "Octopus": [
        "Octopuses, etc. nei",
        "Common octopus",
        "Horned and musky octopuses",
        "Horned octopus",
        "Musky octopus",
        "White-spotted octopus",
        "Octopuses nei",
        "Antarctic octopuses",
    ],
    "Other cephalopods": ["Cephalopods nei"],
    "Other crustaceans": ["Marine crustaceans nei", "Freshwater crustaceans nei"],
    "Other flatfish": ["Flatfishes nei"],
    "Other freshwater fish": ["Freshwater fishes nei"],
    "Other groundfish": ["Groundfishes nei"],
    "Other marine fish": ["Marine fishes nei"],
    "Other non-food use": [],
    "Other products": [],
    "Other salmonids": [],
    "Other sharks": [],  # we can safely assume 100 % marine
    "Oyster": [
        "European flat oyster",
        "Pacific cupped oyster",
        "Cupped oysters nei",
        "Flat oysters nei",
        "Rayed pearl oyster",
    ],
    "Pangasius": [],
    "Plaice, European": ["European plaice"],
    "Pollack": ["Pollack"],
    "Ray": [
        "Rays and skates nei",
        "Thornback ray",
        "Spotted ray",
        "Blonde ray",
        "Small-eyed ray",
        "Undulate ray",
        "Starry ray",
        "Sailray",
        "Sandy ray",
        "Cuckoo ray",
        "Rays, stingrays, mantas nei",
        "Mediterranean starry ray" "Bathyraja rays nei",
        "Shagreen ray",
        "Stingrays nei",
        "Common stingray",
        "Pelagic stingray",
        "Common eagle ray",
        "Torpedo rays",
        "Marbled electric ray",
        "Sharks, rays, skates, etc. nei",
        "Raja rays nei",
        "Round ray",
        "Spinetail ray",
        "Brown ray",
        "Stingrays, butterfly rays nei",
        "Spiny butterfly ray",
        "Madeiran ray",
        "Rough ray",
        "Deep-water ray",
        "Roughtail stingray",
        "Eagle rays nei",
        "Electric rays nei",
    ],
    "Ray’s bream": ["Southern rays bream"],
    "Redfish": [
        "Atlantic redfishes nei",
        "Golden redfish",
        "Beaked redfish",
        "Scorpionfishes, redfishes nei",
        "Redfish",
        "Norway redfish",
        "Cape redfish",
    ],
    "Rock lobster and sea crawfish": [],  # assume 100 % marine
    "Saithe (=Coalfish)": ["Saithe(=Pollock)"],
    "Salmon": ["Salmonoids nei", "Atlantic salmon"],
    "Sardine": [
        "European pilchard(=Sardine)",
        "Sardinellas nei",
        "Round sardinella",
        "Madeiran sardinella",
        "Pacific sardine",
    ],
    "Scallop": [
        "Great Atlantic scallop",
        "Scallops nei",
        "Queen scallop",
        "Great Mediterranean scallop",
        "Variegated scallop",
        "Iceland scallop",
        "Scalloped hammerhead",
        "Club scallop",
        "Patagonian scallop",
    ],
    "Sea cucumber": ["Sea cucumbers nei", "Royal cucumber"],
    "Sea urchin": [
        "European edible sea urchin",
        "Sea urchins, etc. nei",
        "Stony sea urchin",
        "Sea urchins nei",
        "Black sea urchin",
    ],
    "Seabass, European": ["European seabass"],
    "Seabass, other": [
        "Groupers, seabasses nei",
        "Seabasses nei",
        "Spotted seabass",
    ],
    "Seabream, gilthead": [
        "Gilthead seabream",
    ],
    "Seabream, other": [
        "Blackspot seabream",
        "Axillary seabream",
        "Annular seabream",
        "White seabream",
        "Common two-banded seabream",
        "Zebra seabream",
        "Sharpsnout seabream",
        "Saddled seabream",
        "Bluespotted seabream",
        "Panga seabream",
        "Redbanded seabream",
        "Black seabream",
        "Porgies, seabreams nei",
    ],
    "Seaweed and other algae": [
        "Brown seaweeds",
        "Red seaweeds",
        "Green seaweeds",
        "Seaweeds nei",
        "Gelidium seaweeds",
    ],
    "Shrimp Crangon spp": [
        "Crangon shrimps nei",
    ],
    "Shrimp, coldwater": ["Northern prawn"],
    "Shrimp, deep-water rose": ["Deep-water rose shrimp"],
    "Shrimp, miscellaneous": [
        "Common shrimp",
        "Penaeus shrimps nei",
        "Aristeid shrimps nei",
        "Aesop shrimp",
        "Knife shrimp",
        "Pandalus shrimps nei",
        "Palaemonid shrimps nei",
        "Pink glass shrimp",
        "Southern pink shrimp",
        "Speckled shrimp",
        "Giant red shrimp",
        "Blue and red shrimp",
        "Scarlet shrimp",
        "Striped soldier shrimp",
        "Metapenaeus shrimps nei",
        "Guinea shrimp",
        "Megalops shrimp",
        "Striped red shrimp",
        "Pandalid shrimps nei",
        "Armed nylon shrimp",
        "Golden shrimp",
        "Narwal shrimp",
        "Whip shrimp",
        "Palaemon shrimps nei",
        "Atlantic mud shrimp",
        "Jack-knife shrimp",
        "White glass shrimp",
        "Red snapping shrimp",
    ],
    "Shrimp, warmwater": ["Penaeid shrimps nei", "Banana prawn", "Giant river prawn"],
    "Sole, common": ["Common sole"],
    "Sole, other": [
        "Lemon sole",
        "Soles nei",
        "Sand sole",
        "Solenette",
        "Senegalese sole",
        "Wedge sole",
        "Thickback soles nei",
        "Thickback sole",
        "Solen razor clams nei",
        "Black sole",
        "Southeast Atlantic soles nei",
        "Bean solen",
        "Deep water sole",
        "Ocellated wedge sole",
        "Whiskered sole",
        "Portuguese sole",
        "Guinean sole",
        "West coast sole",
        "Foureyed sole",
        "Klein's sole",
        "Cyclope sole",
        "Cadenat's sole",
        "Adriatic sole",
        "Senegalese tonguesole",
        "Guinean tonguesole",
    ],
    "Sprat (=Brisling)": ["European sprat"],
    "Squid": [
        "Inshore squids nei",
        "Common squids nei",
        "European squid",
        "Various squids nei",
        "Cuttlefish, bobtail squids nei",
        "Northern shortfin squid",
        "Patagonian squid",
        "Longfin squid",
        "Cape Hope squid",
        "European common squid",
        "Broadtail shortfin squid",
        "Argentine shortfin squid",
        "European flying squid",
        "Sevenstar flying squid",
        "Veined squid",
        "Neon flying squid",
        "Stout bobtail squid",
        "Dwarf bobtail squid",
        "Common bobtail squid",
        "Alloteuthis squids nei",
        "Midsize squid",
        "Ommastrephidae squids nei",
        "Flying squids nei",
        "Webbed flying squid",
        "Lesser flying squid",
        "Todarodes flying squids nei",
        "Angolan flying squid",
        "Orangeback flying squid",
        "Greater hooked squid",
        "Diamondback squid",
        "Shortfin squids nei",
    ],
    "Surimi": [],
    "Swordfish": ["Swordfish"],
    "Tilapia": [],
    "Toothfish": ["Antarctic toothfish", "Patagonian toothfish"],
    "Trout": ["Sea trout", "Rainbow trout", "Trouts nei"],
    "Tuna, albacore": [
        "Albacore",
    ],
    "Tuna, bigeye": [
        "Bigeye tuna",
    ],
    "Tuna, bluefin": [
        "Pacific bluefin tuna",
        "Southern bluefin tuna",
        "Atlantic bluefin tuna",
    ],
    "Tuna, miscellaneous": [
        "Tuna-like fishes nei",
        "Tunas nei",
        "Dogtooth tuna",
        "Frigate and bullet tunas",
        "Frigate tuna",
        "Bullet tuna",
        "Blackfin tuna",
        "True tunas nei",
        "Longtail tuna",
    ],
    "Tuna, skipjack": [
        "Skipjack tuna",
    ],
    "Tuna, yellowfin": [
        "Yellowfin tuna",
    ],
    "Turbot": ["Turbot", "Turbots nei", "Spiny turbot"],
    "Whiting": ["Whiting"],
}
# %%
# Load data from EUMOFA (exports) and FAO (production)
# =============================================================================
exports = xr.open_dataset("data/economic/exports/exports_nea_countries.nc")
species_eumofa = exports.species

# Create a 2D Dataframe that allows to map between FAO and EUMOFA species
# Columns -> FAO species
# Index -> EUMOFA species (and associated commodity group)
# A one (1) means that the FAO species are mapped to EUMOFA species
# A zero (0) means that the FAO species are NOT mapped to EUMOFA species
species_fao = pd.Index(
    list(itertools.chain.from_iterable(FAO2EUMOFA.values())), name="FAO"
)
n_rows = len(list(FAO2EUMOFA.keys()))
n_columns = len(species_fao)

midx = pd.MultiIndex.from_arrays(
    np.vstack([exports.species.values, exports.commodity_group.values]),
    names=["EUMOFA", "commodity_group"],
)

conversion_table = pd.DataFrame(
    np.empty([n_rows, n_columns]) * np.nan, columns=species_fao, index=midx
)
for species, group in FAO2EUMOFA.items():
    conversion_table.loc[(species), group] = 1

conversion_table.fillna(0, inplace=True)
conversion_table = conversion_table.astype(int)

conversion_table.to_csv(
    "data/economic/production/conversion_table_species_fao_to_eumofa.csv"
)

# %%
